/* queue.mjs — THE REPORT QUEUE. One durable, machine-appendable file that both the
 * playtester (writer) and the triage tool (verifier) own between them.
 *
 *   docs/qa/playtest/queue.json     the truth: one object per finding
 *   docs/qa/playtest/index.html     rendered, with the frames, for a human
 *   docs/qa/playtest-queue.md       the same list in the terminal / in a diff
 *
 * The last two are GENERATED by tools/playtest_triage.mjs. Only queue.json is
 * edited, and only by appending or by updating an entry's `verification`.
 *
 * *** EVERY ENTRY CARRIES A VERIFICATION STATUS AND IT STARTS UNVERIFIED. ***
 * This repo has a documented confabulation scar (the pink plank: a judge described
 * a defect that did not exist, and a builder built against it) and a ratified
 * workflow that came out of it — judge finds a flaw, MEASURE the claim on an
 * instrument, only then build. scene_redteam's own note is that its second stage
 * filters WEAK CRITICISM, not CONFABULATION; nothing an LLM says about a picture is
 * evidence until an instrument agrees.
 *
 *   VERIFIED    an instrument confirmed it. `instrument` names it and `evidence`
 *               carries the line it printed.
 *   REFUTED     an instrument contradicted it. Just as valuable, and counted just
 *               as prominently: the false-positive rate IS the calibration of this
 *               whole tool.
 *   UNVERIFIED  nobody has measured it. A LEAD, NEVER A TICKET.
 *
 * THE SEVERITY FIELD IS THE AGENT'S OPINION, not a triage output. It orders the
 * queue for a human; it does not license anybody to build.
 *
 * REPRO SAVES. Every entry carries the save blob from the moment of the bug plus
 * the commit SHA it was captured at. A bug report that ships with a loadable save
 * is worth ten that do not — and the SHA is what makes a stale one DETECTABLE
 * instead of quietly wrong, which is the failure mode this repo hit four times in
 * one night (a pasted region coordinate, stale routes, an untracked lightrigs.json,
 * a stale bake list).
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';

const ROOT = join(dirname(new URL(import.meta.url).pathname), '../..');
export const QDIR = join(ROOT, 'docs/qa/playtest');
export const QUEUE = join(QDIR, 'queue.json');

export function load() {
  if (!existsSync(QUEUE)) return { version: 1, note: 'see tools/playtest/queue.mjs', entries: [] };
  try { return JSON.parse(readFileSync(QUEUE, 'utf8')); }
  catch (e) { throw new Error('queue.json will not parse: ' + e.message + ' — fix it by hand rather than letting a run overwrite it'); }
}
export function save(q) {
  mkdirSync(QDIR, { recursive: true });
  writeFileSync(QUEUE, JSON.stringify(q, null, 2));
}
export function nextId(q) {
  const day = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  return `PT-${day}-${String(q.entries.filter(e => e.id.includes(day)).length + 1).padStart(3, '0')}`;
}
export function relative(p) { return p ? String(p).replace(ROOT + '/', '') : p; }

/** Append one finding. Returns the stored entry. */
export function append(entry) {
  const q = load();
  const e = { id: nextId(q), created: new Date().toISOString(),
    verification: { status: 'UNVERIFIED', instrument: null, evidence: null, at: null }, ...entry };
  if (!e.verification) e.verification = { status: 'UNVERIFIED', instrument: null, evidence: null, at: null };
  q.entries.push(e); save(q);
  return e;
}
export function update(id, patch) {
  const q = load();
  const i = q.entries.findIndex(e => e.id === id);
  if (i < 0) return null;
  q.entries[i] = { ...q.entries[i], ...patch };
  save(q);
  return q.entries[i];
}
