// cine_map.mjs — draw THE REGION MAP: which camera owns which walkable metre of
// Dellhollow, where each camera stands, and where the cuts are.
//
//   node tools/cine_map.mjs        -> docs/qa/districts/cine_regions.svg
//
// Two panels, because one is a lie about this town. Dellhollow is a canyon WALL: the
// plan view (x across the gorge floor, y from cliff to river) shows the shots' plots
// but stacks the Shelf on top of the Waterfront; the elevation (x, height) shows the
// tier structure that makes the town what it is. A shot's region is drawn in both.
// SVG, not a render: this is a diagram of ownership, and it has to be readable and
// diffable, not pretty.
import fs from 'fs';
import path from 'path';
import {loadCine, walkMeshes, ownerOfWalk, PUB, ROOT, m2r, r2m} from './cine_regions.mjs';

const C = loadCine();
const S = JSON.parse(fs.readFileSync(path.join(PUB, 'townmap/dellhollow.cameras.solved.json'), 'utf8'));
const {meshes} = walkMeshes(path.join(PUB, 'assets/scenes/townwalk/scene.glb'));
for (const m of meshes) m.owner = ownerOfWalk(C, m.name, m.center).cam;

// a colour per shot: evenly spaced hues, alternating lightness so neighbours differ
const COL = {};
S.cameras.forEach((c, i) => {
  const h = Math.round((i * 360 / S.cameras.length + 15) % 360);
  COL[c.id] = `hsl(${h} 62% ${i % 2 ? 42 : 58}%)`;
});

// ---- extents (map coords) ----------------------------------------------------
const ext = {x: [1e9, -1e9], y: [1e9, -1e9], h: [1e9, -1e9]};
const grow = (p) => { ext.x[0] = Math.min(ext.x[0], p[0]); ext.x[1] = Math.max(ext.x[1], p[0]);
  ext.y[0] = Math.min(ext.y[0], p[1]); ext.y[1] = Math.max(ext.y[1], p[1]);
  ext.h[0] = Math.min(ext.h[0], p[2]); ext.h[1] = Math.max(ext.h[1], p[2]); };
for (const m of meshes) { grow(m.min); grow(m.max); }
for (const c of S.cameras) grow(c.pos);
const PAD = 6;
for (const k of ['x', 'y', 'h']) { ext[k][0] -= PAD; ext[k][1] += PAD; }

const SC = 8.2;                                       // px per metre
const Wpx = Math.round((ext.x[1] - ext.x[0]) * SC);
const Hplan = Math.round((ext.y[1] - ext.y[0]) * SC);
const Helev = Math.round((ext.h[1] - ext.h[0]) * SC);
const GAP = 78, TOP = 96, LEG = 30 + Math.ceil(S.cameras.length / 3) * 22;
const Htot = TOP + Hplan + GAP + Helev + LEG + 40;

const px = (x) => ((x - ext.x[0]) * SC).toFixed(1);
const pyPlan = (y) => (TOP + (y - ext.y[0]) * SC).toFixed(1);
const pyElev = (h) => (TOP + Hplan + GAP + (ext.h[1] - h) * SC).toFixed(1);

const o = [];
o.push(`<svg xmlns="http://www.w3.org/2000/svg" width="${Wpx}" height="${Htot}" viewBox="0 0 ${Wpx} ${Htot}" font-family="ui-monospace,Menlo,monospace">`);
o.push(`<rect width="${Wpx}" height="${Htot}" fill="#140f0c"/>`);
o.push(`<text x="16" y="34" fill="#ece0d0" font-size="21" font-weight="700">DELLHOLLOW — the cinematic town: ${S.cameras.length} shots, ${meshes.length} walk surfaces, ${S.cuts.length} camera seams</text>`);
o.push(`<text x="16" y="56" fill="#a89179" font-size="12">Every walkable metre is coloured by the SHOT that owns it. Ownership is by map record (landmark / walk edge), so coverage is total by construction — tools/cine_test.mjs proves it. Generated by tools/cine_map.mjs.</text>`);
o.push(`<text x="16" y="74" fill="#a89179" font-size="12">◆ camera position and aim   ━ camera seam (a silent cut; band drawn to measured width)   Panels: PLAN (x along-gorge, y cliff→river) and ELEVATION (x, height) — the town is a canyon wall, so it needs both.</text>`);

// panel frames + labels
const frame = (y, h, label, sub) => {
  o.push(`<rect x="0.5" y="${y}" width="${Wpx - 1}" height="${h}" fill="#0d0a08" stroke="#3a2c20"/>`);
  o.push(`<text x="10" y="${y - 8}" fill="#e9a24b" font-size="13" font-weight="700">${label}</text>`);
  o.push(`<text x="${10 + label.length * 8.2}" y="${y - 8}" fill="#6b5a49" font-size="11">${sub}</text>`);
};
frame(TOP, Hplan, 'PLAN', ` — x ${ext.x[0].toFixed(0)}..${ext.x[1].toFixed(0)}m along the gorge, y ${ext.y[0].toFixed(0)}..${ext.y[1].toFixed(0)}m from the cliff face out to the river`);
frame(TOP + Hplan + GAP, Helev, 'ELEVATION', ` — x along the gorge, height ${ext.h[0].toFixed(0)}..${ext.h[1].toFixed(0)}m (water ~0, the rim road at 24)`);

// 10 m grid
for (let x = Math.ceil(ext.x[0] / 10) * 10; x < ext.x[1]; x += 10) {
  o.push(`<line x1="${px(x)}" y1="${TOP}" x2="${px(x)}" y2="${TOP + Hplan}" stroke="#241b15"/>`);
  o.push(`<line x1="${px(x)}" y1="${TOP + Hplan + GAP}" x2="${px(x)}" y2="${TOP + Hplan + GAP + Helev}" stroke="#241b15"/>`);
  o.push(`<text x="${px(x)}" y="${TOP + Hplan + GAP + Helev + 13}" fill="#6b5a49" font-size="10" text-anchor="middle">${x}</text>`);
}

// ---- the walk surfaces, coloured by owner -----------------------------------
for (const m of meshes) {
  const c = COL[m.owner] || '#888';
  const w = Math.max(1.4, (m.max[0] - m.min[0]) * SC);
  o.push(`<rect x="${px(m.min[0])}" y="${pyPlan(m.min[1])}" width="${w}" height="${Math.max(1.4, (m.max[1] - m.min[1]) * SC)}" fill="${c}" fill-opacity="0.72"/>`);
  o.push(`<rect x="${px(m.min[0])}" y="${pyElev(m.max[2])}" width="${w}" height="${Math.max(1.4, (m.max[2] - m.min[2]) * SC + 1.4)}" fill="${c}" fill-opacity="0.72"/>`);
}

// ---- the seams --------------------------------------------------------------
for (const c of S.cuts) {
  const a = r2m(c.atRuntime);
  // the band's normal is runtime xz; back to map xy is (nx, -nz)
  const n = [c.band.n[0], -c.band.n[1]];
  const perp = [-n[1], n[0]];
  const x1 = a[0] + perp[0] * c.band.w, y1 = a[1] + perp[1] * c.band.w;
  const x2 = a[0] - perp[0] * c.band.w, y2 = a[1] - perp[1] * c.band.w;
  o.push(`<line x1="${px(x1)}" y1="${pyPlan(y1)}" x2="${px(x2)}" y2="${pyPlan(y2)}" stroke="#ffe9c9" stroke-width="2.4" stroke-opacity="0.9"/>`);
  o.push(`<circle cx="${px(a[0])}" cy="${pyElev(a[2])}" r="2.6" fill="#ffe9c9"/>`);
}

// ---- the cameras ------------------------------------------------------------
for (const c of S.cameras) {
  const col = COL[c.id];
  const [cx, cy, ch] = c.pos, [ax, ay, ah] = c.aim;
  // view cone in plan
  const dx = ax - cx, dy = ay - cy, L = Math.hypot(dx, dy) || 1;
  const half = Math.atan(Math.tan(c.fov * Math.PI / 360) * (C.D.aspect));
  const rot = (ang) => [Math.cos(ang) * (dx / L) - Math.sin(ang) * (dy / L),
                        Math.sin(ang) * (dx / L) + Math.cos(ang) * (dy / L)];
  const r1 = rot(half), r2 = rot(-half), R = L * 1.25;
  o.push(`<path d="M ${px(cx)} ${pyPlan(cy)} L ${px(cx + r1[0] * R)} ${pyPlan(cy + r1[1] * R)} L ${px(cx + r2[0] * R)} ${pyPlan(cy + r2[1] * R)} Z" fill="${col}" fill-opacity="0.09" stroke="${col}" stroke-opacity="0.45" stroke-width="0.8"/>`);
  o.push(`<line x1="${px(cx)}" y1="${pyPlan(cy)}" x2="${px(ax)}" y2="${pyPlan(ay)}" stroke="${col}" stroke-width="1" stroke-dasharray="3 2"/>`);
  for (const [X, Y] of [[px(cx), pyPlan(cy)], [px(cx), pyElev(ch)]])
    o.push(`<path d="M ${X} ${+Y - 5} L ${+X + 5} ${Y} L ${X} ${+Y + 5} L ${+X - 5} ${Y} Z" fill="${col}" stroke="#140f0c" stroke-width="0.8"/>`);
  o.push(`<line x1="${px(cx)}" y1="${pyElev(ch)}" x2="${px(ax)}" y2="${pyElev(ah)}" stroke="${col}" stroke-width="1" stroke-dasharray="3 2"/>`);
  o.push(`<text x="${+px(cx) + 7}" y="${+pyPlan(cy) + 4}" fill="${col}" font-size="10.5" font-weight="700">${c.id}</text>`);
}

// ---- legend -----------------------------------------------------------------
const LY = TOP + Hplan + GAP + Helev + 30;
o.push(`<text x="16" y="${LY}" fill="#a89179" font-size="11">shot  ·  standoff  ·  character px (near..far) of 768  ·  walk surfaces owned</text>`);
S.cameras.forEach((c, i) => {
  const col = i % 3, row = Math.floor(i / 3);
  const X = 16 + col * Math.floor((Wpx - 40) / 3), Y = LY + 18 + row * 22;
  o.push(`<rect x="${X}" y="${Y - 9}" width="11" height="11" fill="${COL[c.id]}"/>`);
  o.push(`<text x="${X + 17}" y="${Y}" fill="#ece0d0" font-size="11.5">${c.id}${c.entry ? ' ★' : ''}${c.transit ? ' (transit)' : ''}</text>`);
  o.push(`<text x="${X + 17 + 128}" y="${Y}" fill="#a89179" font-size="11">${c.dist}m · ${c.charPxNear}..${c.charPxFar}px · ${c.walkMeshes} surf</text>`);
});
o.push('</svg>');

const OUT = path.join(ROOT, 'docs/qa/districts/cine_regions.svg');
fs.mkdirSync(path.dirname(OUT), {recursive: true});
fs.writeFileSync(OUT, o.join('\n') + '\n');
console.log(`wrote docs/qa/districts/cine_regions.svg  (${Wpx}x${Htot}, ${S.cameras.length} shots, ${meshes.length} surfaces, ${S.cuts.length} seams)`);
