#!/bin/bash
# Chapter One scene paintings — J3 style, 16:9
cd "$(dirname "$0")/.."
STYLE="Art style: EXACTLY the style of the reference image — premium anime film background, cel-shaded look, painted textures under clean shapes, cinematic glow. 3/4 top-down RPG view, building facades visible where present. No characters, no people, no animals, no text, no labels, no UI, no borders, no watermark, no signature. Image fills the frame edge to edge."

node tools/genart.mjs public/assets/scene-forest.png --ref public/assets/jrpg-3.png --ar 16:9 "$STYLE Scene: a wild forest road at deep dusk. Dense towering autumn forest, cold blue-violet evening mist drifting between the trunks, a narrow overgrown dirt road running continuously from the LEFT edge of the image to the RIGHT edge, mossy boulders, gnarled roots crossing the path, scattered fireflies, faint warm amber light far away at the right edge. Mysterious, hushed, a little ominous — the wild before the village. No buildings."

node tools/genart.mjs public/assets/scene-entrance.png --ref public/assets/jrpg-3.png --ar 16:9 "$STYLE Scene: the edge of a village at dusk where forest gives way to warmth. The dirt road runs continuously from the LEFT edge (dark cold forest) to the RIGHT edge (warm glow). At center stands an old grey stone WAYSTONE beside the road, mossy, with a cracked carved face. To the right: thinning trees, a simple wooden village arch or palisade entrance, the warm amber glow of festival lanterns spilling from beyond the right edge, one or two rooftops visible. Left half cold and wild, right half warm and welcoming — a threshold."

node tools/genart.mjs public/assets/scene-lane.png --ref public/assets/jrpg-3.png --ar 16:9 "$STYLE Scene: a quiet village lane at dusk. On the LEFT: a small thatched-roof stone cottage with warmly lit windows, its wooden door facing the lane, a low wooden fence and tiny herb garden. The dirt lane runs from the cottage door area continuously to the RIGHT edge of the image. Lower-right: a calm dark pond with a short wooden dock, reeds, dusk light reflecting on the water. One iron lamp post beside the lane with its lamp UNLIT (dark glass, no glow). Cozy, sleepy corner of the village."

node tools/genart.mjs public/assets/scene-square.png --ref public/assets/blockout-square.png --ref public/assets/jrpg-3.png --ar 16:9 "The FIRST reference image is a layout draft of a village square scene. The SECOND is the art style target. Paint the layout as a finished scene in EXACTLY the second image's style — premium anime film background, warm dusk festival glow, cel-shaded look. Keep the draft's layout: diamond cobblestone plaza; stone pedestal with glowing amber crystal at dead center; bakery with RED tiled roof upper-left, door facing the plaza; large elder's hall with dark SLATE roof upper-right, door facing the plaza; thatched cottage lower-right; two red-and-white striped market stalls; wooden notice board and crates near the left road; dense autumn forest edges. CRITICAL: THREE clear open roads exit the plaza — bottom-center edge, left-center edge, and top-center edge — keep all three visible and unobstructed. The iron lamp posts are present but UNLIT (dark glass, no glow from lamps). Strings of glowing paper lanterns and triangle bunting span above the plaza. No characters, no people, no text, no watermark, no signature."

node tools/genart.mjs public/assets/scene-gate.png --ref public/assets/jrpg-3.png --ar 16:9 "$STYLE Scene: an ancient stone gate in a dead grey forest, everything drained of color — cold desaturated grey-blue palette, thin mist, a few faint grey moths in the air. The gate stands at the TOP-CENTER: two tall mossy stone pillars and an arch carved with TWO circular interlocking sigil emblems, heavy dark wooden doors CLOSED. An overgrown road runs from the BOTTOM edge of the image up to the gate. Set into the ground before the gate, flanking the road symmetrically left and right, are two round carved stone SIGIL PLATES. One iron lamp post beside the road, unlit. Somber, hushed, forsaken."

echo "=== batch 1 done ==="
