"""owdraft_export.py — bundle the DRAFT corridor as a parallel ow-style scene.

  Blender --python-exit-code 1 -b tools/blends/owdraft-embercorridor.blend \
          -P tools/owdraft_export.py

Writes public/assets/scenes/ow-embercorridor-draft/{scene.glb, meta.json,
zones.json, background.png, stylized.png}.

  *** PROPOSAL DRAFT. NOT CANON, AND NOT WIRED IN. ***
  The scene key ow-embercorridor-draft appears in NO scenegraph, NO world.json
  region and NO chapter script — nothing loads it.  It exists so the proposal can
  be walked if the user wants to, and deleted in one `rm -rf` if not.

It follows the ow-valley bundle contract so it COULD be loaded by play3d.html
unchanged: every mesh that is not water_* / lm_ / veg_ is standable and blocking,
walk_* is the walk network, veg_* is collision-free, zones.json beside scene.glb
is the encounter geography.  spawn is pinned at the Old Gate facing down the gorge,
because that is the frame this whole draft exists to argue about.
"""
import bpy
import contextlib
import io
import json
import math
import os
import shutil
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import owdraft_lib as DL

ROOT = DL.ROOT
KEY = DL.KEY
OUT = os.path.join(ROOT, "public/assets/scenes", KEY)
os.makedirs(OUT, exist_ok=True)

sc = bpy.data.scenes["embercorridor"]
if bpy.context.window:
    bpy.context.window.scene = sc

shot = os.path.join(DL.QA, "embercorridor_aerial.png")
for nm in ("background.png", "stylized.png"):
    if os.path.exists(shot):
        shutil.copyfile(shot, os.path.join(OUT, nm))

# ---- zones.json: same schema and registry order as the shipped ow-valley grid,
# with ONE draft-only type appended ('farm') — appending at the end is the
# contract, and the hanging valley being farmed is half the proposition.
F = DL.DraftField()
cell = 1.25
zg, cell, cols, rows = DL.zone_grid(F, cell)
rle = []
for r in range(rows):
    row = zg[r]
    out, run, cur = [], 0, int(row[0])
    for v in row:
        v = int(v)
        if v == cur:
            run += 1
        else:
            out += [cur, run]
            cur, run = v, 1
    out += [cur, run]
    rle.append(out)
cov = {n: round(float((zg == i).mean() * 100), 2) for i, n in enumerate(DL.ZONES)}

json.dump({
    "_doc": [
        "*** PROPOSAL DRAFT ZONE GRID — NOT CANON ***",
        "Terrain zone grid for the draft corridor tile, same schema as the shipped",
        "ow-valley zones.json.  AXES: runtime/three.js (+x east, +z south);",
        "blender y = -z.  col = floor((x - origin[0]) / cell), row = floor((z -",
        "origin[1]) / cell).  'types' is the registry and cells store indices;",
        "'farm' is APPENDED at the end (index 5), which is how the registry is",
        "meant to grow.  Derived from docs/qa/overworld-draft/"
        "embercorridor-draft.region.json by tools/owdraft_lib.zone_grid.",
    ],
    "draft": True,
    "cell": cell, "origin": [-DL.CX, -DL.CY], "cols": cols, "rows": rows,
    "types": DL.ZONES,
    "colors": ["9ec45a", "2c6b33", "c47a3c", "d9c48f", "2f7f96", "c6ae52"],
    "coverage_pct": cov,
    "rows_rle": rle,
}, open(os.path.join(OUT, "zones.json"), "w"), separators=(",", ":"))

# ---- meta.json: spawn at the Old Gate, facing down the gorge
lm = {l["id"]: l for l in DL.D["landmarks"]}
gx, gy, gz = lm["old-gate"]["pos"]
tx, ty = lm["ember-falls"]["pos"][:2]
json.dump({
    "_doc": [
        "*** PROPOSAL DRAFT BUNDLE — NOT CANON, NOT REFERENCED BY ANY SCENEGRAPH ***",
        "spawn is [x, y, z] in runtime coords (+x east, +y up, +z south); camYaw is",
        "the follow-camera orbit yaw in radians.  Same contract as the ow-valley",
        "bundle so play3d.html could load this unchanged — nothing asks it to.",
        "Regenerated by tools/owdraft_export.py; do not hand-edit.",
    ],
    "draft": True,
    "region": "embercorridor-draft",
    "spawn": [gx - DL.CX, float(F.height(gx, gy)) + 0.1, -(gy - DL.CY)],
    "camYaw": round(math.atan2(tx - gx, -(ty - gy)), 4),
    "spawn_note": "the Old Gate, facing down the gorge toward Dellhollow",
    "portals": {l["id"]: [l["pos"][0], l["pos"][1], l["pos"][2]]
                for l in DL.D["landmarks"] if l["class"] in ("portal", "town", "exit")},
}, open(os.path.join(OUT, "meta.json"), "w"), indent=1)

# ---- scene.glb
for o in list(sc.objects):
    if o.type == "CAMERA" or o.name.startswith("ref_char"):
        bpy.data.objects.remove(o, do_unlink=True)
for o in sc.objects:
    o.select_set(True)
glb = os.path.join(OUT, "scene.glb")
with contextlib.redirect_stdout(io.StringIO()):
    bpy.ops.export_scene.gltf(filepath=glb, export_format="GLB",
                              use_selection=False, export_apply=True,
                              export_yup=True)
print("BUNDLED %s  glb %.1f MB  zones %d x %d  %s"
      % (OUT, os.path.getsize(glb) / 1e6, cols, rows,
         " ".join("%s=%.0f%%" % (k, v) for k, v in cov.items())))
