#!/usr/bin/env node
/* playtest_bench.mjs — SCORE MODELS ON RECORDED OBSERVATIONS, WITHOUT THE GAME.
 *
 *   node tools/playtest_bench.mjs --models=gemini:gemini-3.6-flash,gemini:gemini-3.5-flash-lite
 *   node tools/playtest_bench.mjs --run=run-20260803-0210 --n=20
 *   node tools/playtest_bench.mjs --list                       what is in the golden set
 *
 * WHY. The user wants a cost/effectiveness Pareto across models, and a full episode
 * is twenty minutes of Chrome plus a contended machine. Because layer 1 (the agent)
 * is a clean seam — an observation in, an intent out — the same observation can be
 * replayed through any model with no game running at all. A model comparison
 * becomes minutes of API calls instead of hours of gameplay.
 *
 * THE GOLDEN SET is docs/qa/playtest/runs/<run>/observations.jsonl, written by
 * tools/playtest/episode.mjs: one line per decision carrying the frame, the exact
 * text that was on screen, the history, the intent chosen, AND THE OUTCOME the
 * adapter measured. The outcome is what makes it a benchmark rather than a log:
 *
 *   a `goto` whose leg ARRIVED is a waypoint that provably worked. It is the label.
 *   a `goto` that stalled is NOT a negative label — the world may simply be blocked
 *     there, which is a bug in the game, not a bad decision. It is excluded.
 *   an `advance` that read lines is a correct read of "a dialogue box is open".
 *
 * WHAT IS SCORED
 *   action agreement   did the candidate pick the same KIND of action on the same
 *                      screen. This is the cheap, robust signal.
 *   waypoint error     for goto rows, the distance in normalised image coordinates
 *                      between the candidate's first waypoint and the one that
 *                      provably worked. THIS IS THE HARD PART for this task: it is
 *                      spatial grounding on a dark pre-rendered plate, not
 *                      classification, and it is where cheap models fail.
 *   tokens, latency, estimated cost  the other axis of the Pareto.
 *
 * *** ITS LIMIT, AND IT IS A REAL ONE: FULL EPISODES DIVERGE. *** A model that
 * decides differently at step 12 sees a different step 13, so agreeing with a
 * recorded good decision is NECESSARY, NOT SUFFICIENT. A model could score well
 * here and still play badly — it might make good local choices and never form a
 * plan, and nothing in a single-step replay can see that. THE SHAPE IS TWO STAGES:
 * cheap single-step scoring to SHORTLIST, then a full episode to VALIDATE the
 * survivors. Never promote a model on this number alone.
 *
 * A second honest caveat: the golden set is generated BY a model, so a waypoint
 * that "provably worked" is one that worked, not the best one available. It
 * measures agreement with a competent decision, not optimality.
 */
import { readFileSync, readdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { makeModel, Usage, parseJson, priceOf } from './playtest/models.mjs';
import { decisionPrompt, normalise } from './playtest/agent.mjs';
import { PERSONA } from './playtest/adapter_emberbrook.mjs';

const ROOT = join(dirname(new URL(import.meta.url).pathname), '..');
const argv = process.argv.slice(2);
const arg = (k, d) => { const h = argv.find(a => a.startsWith('--' + k + '=')); return h ? h.split('=').slice(1).join('=') : d; };
const has = (k) => argv.includes('--' + k);
const RUNS = join(ROOT, 'docs/qa/playtest/runs');
const N = parseInt(arg('n', '15'), 10);
const REPS = parseInt(arg('reps', '1'), 10);
const MODELS = arg('models', 'gemini:gemini-3.6-flash').split(',').map(s => s.trim()).filter(Boolean);

function newestRun() {
  if (!existsSync(RUNS)) return null;
  const ds = readdirSync(RUNS).filter(d => existsSync(join(RUNS, d, 'observations.jsonl'))).sort();
  return ds.length ? ds[ds.length - 1] : null;
}
const RUN = arg('run', newestRun());
if (!RUN) { console.error('no run with an observations.jsonl under docs/qa/playtest/runs — play an episode first.'); process.exit(2); }
const OBS = join(RUNS, RUN, 'observations.jsonl');

/* A row is usable when the game measured that the decision WORKED. */
function label(o) {
  const a = o.intent && o.intent.action;
  const L = o.outcome;
  // A waypoint that ARRIVED is obviously good. So is one the GAME interrupted after
  // most of the distance was closed — a camera cut or a story beat firing mid-walk
  // is the game agreeing that you were going somewhere it cared about, and throwing
  // those rows away would bias the golden set against every interesting decision.
  if (a === 'goto' && L && o.intent.waypoints?.length &&
      (L.arrived || (L.reason === 'modal' && L.intended > 1 && L.closed / L.intended >= 0.7)))
    return { action: 'goto', waypoint: o.intent.waypoints[0] };
  if (a === 'advance' && o.outcome && o.outcome.lines > 0) return { action: 'advance' };
  if (a === 'interact' || a === 'choose') return null;      // no measured outcome
  return null;
}
const rows = readFileSync(OBS, 'utf8').trim().split('\n').filter(Boolean).map(l => JSON.parse(l))
  .map(o => ({ o, lab: label(o) })).filter(x => x.lab && x.o.frame && existsSync(join(ROOT, x.o.frame)));

if (has('list')) {
  console.log(`golden set: ${RUN}  (${rows.length} labelled of ${readFileSync(OBS, 'utf8').trim().split('\n').length} steps)`);
  for (const { o, lab } of rows)
    console.log(`  step ${String(o.step).padStart(3)}  ${lab.action.padEnd(8)} ${lab.waypoint ? '[' + lab.waypoint.map(v => v.toFixed(2)).join(',') + ']' : ''}  ${(o.intent.goal || '').slice(0, 60)}`);
  process.exit(0);
}
if (!rows.length) { console.error(`no labelled rows in ${OBS}. A row is labelled when the adapter MEASURED that the decision worked.`); process.exit(2); }

const sample = rows.slice(0, N);
console.log(`playtest_bench — ${sample.length} labelled observations from ${RUN}, ${REPS} rep(s), ${MODELS.length} model(s)`);
console.log('  A FILTER, NOT A VERDICT: episodes diverge, so this shortlists — it never promotes.\n');

const results = [];
for (const spec of MODELS) {
  let model;
  try { model = makeModel(spec); } catch (e) { console.error(`  ${spec}: ${e.message}`); continue; }
  const usage = new Usage();
  let actionHit = 0, tried = 0, malformed = 0, errors = 0;
  const wpErr = [];
  for (let rep = 0; rep < REPS; rep++) for (const { o, lab } of sample) {
    const obs = { screenshot: { mime: 'image/jpeg', data: readFileSync(join(ROOT, o.frame)).toString('base64') },
      text: o.text, history: o.history || [], brief: o.brief || null, nudge: null };
    // BYTE-IDENTICAL PROMPT. A benchmark that re-words the question is measuring
    // the wording, so this calls the agent's own prompt builder.
    const prompt = decisionPrompt(obs, PERSONA);
    let j;
    try {
      const r = await model.ask({ images: [obs.screenshot], text: prompt, temperature: 0.55 });
      usage.add(model.id, r.usage);
      j = normalise(parseJson(r.text));
    } catch (e) { errors++; continue; }
    tried++;
    if (j.malformed) malformed++;
    if (j.action === lab.action) {
      actionHit++;
      if (lab.action === 'goto' && j.waypoints?.length)
        wpErr.push(Math.hypot(j.waypoints[0][0] - lab.waypoint[0], j.waypoints[0][1] - lab.waypoint[1]));
    }
  }
  const med = a => { const s = a.slice().sort((x, y) => x - y); return s.length ? +s[s.length >> 1].toFixed(3) : null; };
  const r = { model: model.id, tried, actionAgreement: tried ? +(actionHit / tried).toFixed(3) : null,
    waypointMedianErr: med(wpErr), waypointN: wpErr.length, malformed, errors,
    tokensIn: usage.in, tokensOut: usage.out + usage.thought,
    secPerCall: tried ? +(usage.ms / 1000 / tried).toFixed(1) : null,
    usdPerCall: tried ? +(usage.estUSD() / tried).toFixed(5) : null,
    usdPer100Steps: tried ? +((usage.estUSD() / tried) * 100).toFixed(2) : null };
  results.push(r);
  console.log(`  ${r.model.padEnd(34)} action ${String(r.actionAgreement).padEnd(6)}  ` +
    `wp-err ${String(r.waypointMedianErr ?? '-').padEnd(6)} (n=${r.waypointN})  ` +
    `${r.secPerCall}s/call  $${r.usdPer100Steps}/100 steps`);
}

console.log('\n== BENCH ' + RUN);
console.log('  action agreement   how often it chose the same KIND of action on the same screen (1.0 = always)');
console.log('  wp-err             median distance, in NORMALISED image units, from a waypoint that provably');
console.log('                     worked. 0.05 is a few centimetres of screen; 0.30 is a different part of');
console.log('                     the picture. This is the spatial signal, and it is the hard one.');
console.log('  cost               ASSUMED prices (tools/playtest/models.mjs). Tokens are the measurement.');
console.log('\n' + JSON.stringify(results, null, 2));
console.log('\n  Shortlist on this. VALIDATE with a full episode before pinning anything.');
