"""valley_export.py — bundle the valley region into the playable scene.

  Blender -b tools/blends/overworld-valley.blend -P tools/valley_export.py

Produces public/assets/scenes/ow-valley/{background.png, stylized.png, scene.glb,
meta.json} alongside the zones.json the build script already wrote there.

Runtime contract (public/play3d.html), inherited unchanged from round 3:
  * every mesh that is NOT water_* / lm_ / veg_ is standable AND blocking
  * walk_* meshes are the designed walk network and drive spawn placement
  * veg_* is removed from collision entirely, so canopies must be separate meshes
    from their trunks (they are: tree_*_trunks stay solid)
  * zones.json beside scene.glb is the encounter geography
NEW here: meta.json pins the SPAWN at the emberbrook-gate portal facing down the
road, because a 280 x 200u region's centre-of-walk-bbox fallback lands nowhere in
particular and chapter 1 starts at that gate.
"""
import bpy
import contextlib
import io
import json
import math
import os
import re
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import valley_map as VM

ROOT = VM.ROOT
KEY = "ow-valley"
OUT = os.path.join(ROOT, "public/assets/scenes", KEY)
os.makedirs(OUT, exist_ok=True)

shot = os.path.join(ROOT, "docs/qa/overworld/valley_overview.png")
for nm in ("background.png", "stylized.png"):
    shutil.copyfile(shot, os.path.join(OUT, nm))

sc = bpy.data.scenes["valley"]
if bpy.context.window:
    bpy.context.window.scene = sc
keep = set(sc.objects)
for o in list(bpy.data.objects):
    if o not in keep:
        bpy.data.objects.remove(o, do_unlink=True)
# render-only scaffolding: the 1.45u scale capsules and the QA zone overlay (the
# runtime builds its own overlay from zones.json)
for o in list(sc.objects):
    if o.name.startswith("ref_char") or o.name.startswith("qa_"):
        bpy.data.objects.remove(o, do_unlink=True)
for o in list(sc.objects):
    for attr in ("name",):
        pass
    o.name = re.sub(r"__valley(\.\d+)?$", "", o.name)
    if o.data and hasattr(o.data, "name"):
        o.data.name = re.sub(r"__valley(\.\d+)?$", "", o.data.name)
for o in sc.objects:
    o.name = re.sub(r"\.\d+$", "", o.name)
    if o.data and hasattr(o.data, "name"):
        o.data.name = re.sub(r"\.\d+$", "", o.data.name)

cam = sc.objects.get("cam_overview")
if cam:
    sc.camera = cam

# ---- the spawn pin: the emberbrook-gate portal, facing down the road ----------
# BY PORTAL LOOKUP, not road index: v2 prepended the Whisperwood entrance to the
# road, so a fixed "index 2" silently became the map edge (verify caught it).
import numpy as np
F = VM.ValleyField()
_gb = VM.w2b(*VM.PORTALS["emberbrook-gate"]["at"][:2])
i = int(np.argmin(np.hypot(F.road[:, 0] - _gb[0], F.road[:, 1] - _gb[1])))
i = max(0, min(len(F.road) - 3, i))
bx, by = float(F.road[i, 0]), float(F.road[i, 1])
bz = float(F.road_h[i]) + 0.12
tg = F.road[i + 2] - F.road[i]
tg = tg / (tg[0] ** 2 + tg[1] ** 2) ** 0.5
# runtime is +x east / +z south, so runtime z = -blender y.  ORBIT.yaw places the
# camera at (cos yaw, sin yaw) from the target, so the VIEW direction is its
# negation: yaw = atan2(tg_z, -tg_x) points the camera down the road.
spawn = [bx, bz, -by]
yaw = math.atan2(-float(tg[1]), -float(tg[0]))
meta = {
    "_doc": ["Bundle metadata for the valley region. spawn is [x, y, z] in runtime "
             "coords (+x east, +y up, +z south); camYaw is the initial follow-camera "
             "orbit yaw in radians. Both are read by public/play3d.html.",
             "Regenerated by tools/valley_export.py from the map files — do not hand-edit."],
    "region": VM.REGION_ID,
    "spawn": spawn,
    "camYaw": round(yaw, 4),
    "spawn_note": "emberbrook-gate portal, facing down the road to Dellhollow",
    "portals": {k: v["at"] for k, v in VM.PORTALS.items()},
}
json.dump(meta, open(os.path.join(OUT, "meta.json"), "w"), indent=1)

meshes = [o for o in sc.objects if o.type == "MESH"]
tris = sum(sum(len(p.vertices) - 2 for p in o.data.polygons) for o in meshes)
walk = sorted(o.name for o in meshes if o.name.lower().startswith("walk"))
water = sorted(o.name for o in meshes if o.name.lower().startswith("water_"))
veg = sorted(o.name for o in meshes if o.name.lower().startswith("veg_"))
fx = sorted(o.name for o in meshes if o.name.lower().startswith("fx_"))

kw = dict(filepath=os.path.join(OUT, "scene.glb"), export_format="GLB",
          export_yup=True, export_cameras=True, export_lights=False,
          export_apply=True, export_vertex_color="ACTIVE", use_active_scene=True,
          export_materials="EXPORT", export_image_format="JPEG")
while True:
    try:
        with contextlib.redirect_stdout(io.StringIO()):
            bpy.ops.export_scene.gltf(**kw)
        break
    except TypeError as e:
        m = re.search(r'"([A-Za-z_]+)"', str(e)) or re.search(r"'([A-Za-z_]+)'", str(e))
        if m and m.group(1) in kw:
            print("  (exporter does not accept %s — dropping)" % m.group(1))
            kw.pop(m.group(1))
            continue
        raise

sz = os.path.getsize(os.path.join(OUT, "scene.glb")) / 1e6
zp = os.path.join(OUT, "zones.json")
print("EXPORT OK %s | %d meshes | %d tris | glb %.2f MB | cam=%s"
      % (KEY, len(meshes), tris, sz, cam.name if cam else "-"))
print("  walk_:  %s" % ", ".join(walk))
print("  water_: %s" % ", ".join(water))
print("  veg_:   %s" % ", ".join(veg))
print("  fx_:    %s" % ", ".join(fx))
print("  spawn:  runtime %s  camYaw %.3f rad" % ([round(v, 2) for v in spawn], yaw))
print("  zones.json: %s" % ("%.1f kB" % (os.path.getsize(zp) / 1e3)
                            if os.path.exists(zp) else "*** MISSING"))
print("  URL:    play3d.html?scene=%s&rt=1" % KEY)
